kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# NEW: Force a specific, stable Kubernetes version
# You can change this to v1.28.0 or v1.29.2 if v1.30.0 has issues
name: my-jenkins-cluster
nodes:
- role: control-plane
  image: kindest/node:v1.29.2 # Pinning to a stable version
  extraPortMappings:
  - containerPort: 80
    hostPort: 8070
    listenAddress: "0.0.0.0"
    protocol: TCP
